
platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'BeeFun' do
    
	use_frameworks!
#    pod 'Zip'
	pod 'Alamofire'
	pod 'IQKeyboardManagerSwift'
    pod 'SnapKit'
    pod 'Moya'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'MBProgressHUD'
#    pod 'SVProgressHUD'
    pod 'HMSegmentedControl'
    pod 'SwiftyJSON'
    pod 'SwiftyBeaver'
    pod 'MJRefresh'
#    pod 'iCloudDocumentSync'
    pod 'SwiftDate'
#	pod 'Bugly'
#    pod 'PromiseKit', '~> 4.0'
    pod 'SwiftMessages'
    pod 'JPush'
#    pod 'AVOSCloud'
    pod 'TOWebViewController'
    # Fabric 服务
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftLint'
    pod 'SQLite.swift'
    pod 'iCarousel'
    pod 'SwipeCellKit'
    pod 'ReachabilitySwift'
    pod "Kanna"
    #    pod 'Reveal-SDK', :configurations => ['Debug']
    #    pod 'GodEye', '~> 1.0.0', :configurations => ['Debug']  现在该库不能使用，待更新后再重启该库
    pod 'GDPerformanceView-Swift', '~> 1.3.2', :configurations => ['Debug']
    pod 'YYText'
    pod 'OAuthSwift'
    pod 'SwiftyStoreKit'
#    pod 'RxSwift'
#    pod 'RxCocoa'
    pod 'SkeletonView'
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            if [ 'SwiftDate'].include?(target.name)
#                config.build_settings['SWIFT_VERSION'] = "2.3"
#            end
#        end
#    end
#end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '3.2'
#        end
#    end
#end

