
platform :ios, '9.0'

target 'Coderpursue' do
	use_frameworks!

	pod 'Alamofire'
	pod 'IQKeyboardManagerSwift'
    pod 'SnapKit'
    pod 'Moya', git: 'https://github.com/Moya/Moya.git', tag: '8.0.0-beta.1'
    pod 'ObjectMapper', '~> 2.0.0'
    pod 'Kingfisher'
	#pod 'Former'
	#pod 'EZSwiftExtensions'
	#pod 'XCGLogger'
    pod 'ReachabilitySwift', '~> 3'
    #pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
	#pod 'PullToBounce'
	pod 'MBProgressHUD'
	pod 'MJRefresh'
    pod 'SwiftDate', :git => 'https://github.com/malcommac/SwiftDate.git', :branch => 'feature/swift-3.0'
	pod 'Bugly'
    #pod 'UMengAnalytics-NO-IDFA'
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            if [ 'SwiftDate'].include?(target.name)
#                config.build_settings['SWIFT_VERSION'] = "2.3"
#            end
#        end
#    end
#end
