
platform :ios, '9.0'

target 'Coderpursue' do
	use_frameworks!

	pod 'Alamofire'
	pod 'IQKeyboardManagerSwift'
    pod 'SnapKit'
    pod 'Moya'
    pod 'ObjectMapper', '~> 2.2'
    pod 'Kingfisher'
	#pod 'Former'
	#pod 'EZSwiftExtensions'
	#pod 'XCGLogger'
    pod 'ReachabilitySwift', '~> 3'
    #pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
	#pod 'PullToBounce'
	pod 'MBProgressHUD'
	pod 'MJRefresh'
    pod 'SwiftDate', '~> 4.0'
	pod 'Bugly'
    pod "PromiseKit", "~> 4.0"
    pod 'SwiftMessages'
    #pod 'UMengAnalytics-NO-IDFA'
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            if [ 'SwiftDate'].include?(target.name)
#                config.build_settings['SWIFT_VERSION'] = "2.3"
#            end
#        end
#    end
#end
